let workspace = '';
EasmIpAddressAsset
|where WorkspaceName == workspace
|union kind=inner (EasmHostAsset | where WorkspaceName == workspace)
|mv-expand Locations
|extend Region = tostring(Locations.Region), City = tostring(Locations.City), Latitude = toreal(Locations.Latitude), Longitude = toreal(Locations.Longitude), LocationLastSeen = todatetime(Locations.LastSeen), LocationFirstSeen = todatetime(Locations.FirstSeen)
|where isnotempty(Latitude) and isnotempty(Longitude) and isnotempty(Region) and isnotempty(City)
|project-keep AssetName,Region,City,Latitude,Longitude,LocationFirstSeen,LocationLastSeen
|summarize hint.strategy=shuffle arg_max(LocationLastSeen, *) by AssetName,Region,City,Latitude,Longitude
//|summarize Count=count() by Region,City