let workspace = '{_easm_workspace_name}';
let lastseen = 30d;
let oldestsnapshot = EasmAsset|where WorkspaceName == workspace|summarize by SnapshotDateTime|sort by SnapshotDateTime asc|take 1;
EasmHostAsset
|where WorkspaceName == workspace
|join kind=anti oldestsnapshot on SnapshotDateTime
|summarize hint.strategy=shuffle arg_max(SnapshotDateTime, *) by AssetUuid
|extend Domain = iff(isnotempty(Domain), Domain, Host)
|summarize Count=count() by Domain
|sort by Count {_easm_host_sort_order}