let workspace = '';
let Name = tostring(parse_json('{selected_web_component}').Name);
let Version = tostring(parse_json('{selected_web_component}').Version);
EasmAssetWebComponent
|where WorkspaceName == workspace
|where AssetLastSeen > ago(60d) and WebComponentLastSeen > ago(60d)
|where WebComponentName == Name and WebComponentVersion == Version
|extend Category = WebComponentCategory
|summarize hint.strategy=shuffle arg_max(SnapshotDateTime, *) by AssetName,Name,Version
|project-keep AssetName,Name,Version,Category,AssetLastSeen