let workspace = '';
//let lastseen = > ago(60d);
EasmRisk
|where WorkspaceName == workspace
|where AssetLastSeen > ago(60d)
|where CategoryName startswith_cs 'Low'
|extend Priority = 'Low'
|project-keep Priority,MetricDisplayName,SnapshotDateTime,AssetName
|summarize hint.strategy=shuffle arg_max(SnapshotDateTime, *) by Priority,MetricDisplayName,AssetName
|summarize Count=count() by Priority,MetricDisplayName
|order by Count desc 